import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      colors: {
        bg: {
          primary: "#0F1419",
          secondary: "#16181D",
          tertiary: "#1C1F26",
          elevated: "#22252D",
          overlay: "rgba(0, 0, 0, 0.65)",
        },
        accent: {
          gold: "#FFD700",
          "gold-hover": "#E6C200",
          blue: "#00D9FF",
          "blue-hover": "#00B8D9",
          green: "#00FF88",
          red: "#FF3B5C",
          "red-hover": "#E6334F",
          orange: "#FF9500",
          purple: "#A855F7",
        },
        text: {
          primary: "#FFFFFF",
          secondary: "#B8C5D6",
          tertiary: "#6B7A94",
          disabled: "#3D4A5C",
        },
        border: {
          default: "#2A3654",
          muted: "#1F2937",
          focus: "#00D9FF",
          error: "#FF3B5C",
        },
        status: {
          live: "#FF3B5C",
          scheduled: "#FF9500",
          finished: "#00FF88",
          draft: "#6B7A94",
          disabled: "#3D4A5C",
        },
        button: {
          "primary-bg": "#FFD700",
          "primary-hover": "#E6C200",
          "primary-text": "#0F1419",
          "secondary-bg": "#00D9FF",
          "secondary-hover": "#00B8D9",
          "secondary-text": "#0F1419",
          "danger-bg": "#FF3B5C",
          "danger-hover": "#E6334F",
          "danger-text": "#FFFFFF",
          "ghost-bg": "transparent",
          "ghost-hover": "#1C1F26",
          "ghost-text": "#B8C5D6",
        },
      },
      spacing: {
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "8": "32px",
        "10": "40px",
        "12": "48px",
        "16": "64px",
        "20": "80px",
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(0, 0, 0, 0.3)",
        md: "0 4px 6px rgba(0, 0, 0, 0.4)",
        lg: "0 10px 15px rgba(0, 0, 0, 0.5)",
        xl: "0 20px 25px rgba(0, 0, 0, 0.6)",
        "glow-gold": "0 0 20px rgba(255, 215, 0, 0.3)",
        "glow-blue": "0 0 20px rgba(0, 217, 255, 0.3)",
        "glow-red": "0 0 20px rgba(255, 59, 92, 0.3)",
      },
      fontSize: {
        display: ["48px", { lineHeight: "56px", fontWeight: "700" }],
        h1: ["32px", { lineHeight: "40px", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "32px", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "28px", fontWeight: "600" }],
        h4: ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        body: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        label: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        caption: ["11px", { lineHeight: "14px", fontWeight: "400" }],
        code: ["14px", { lineHeight: "20px" }],
      },
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
      },
    },
  },
  plugins: [],
};

export default config;
